version: "3.8"

services:
  php:
    build: .
    container_name: symfony34_php
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/var
      - /var/www/web/bundles
    ports:
      - "8000:8000"  # <-- expose le port 8000 du conteneur
    working_dir: /var/www
    command: tail -f /dev/null
