# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

        AppBundle\Entity\Etudiant:
            algorithm: bcrypt

        AppBundle\Entity\Parents:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        app_student_provider:
            entity:
                class: AppBundle:Etudiant
                property: telephone

        app_parent_provider:
            entity:
                class: AppBundle:Parents
                property: telephone

        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_student_area:
            pattern: ^/espace/etudiant/login$
            anonymous: true

        login_parent_area:
            pattern: ^/espace/parent/login$
            anonymous: true

        login_area:
            pattern: ^/login$
            anonymous: true

        student_space:
            pattern: ^/espace/etudiant/
            anonymous: false
            form_login:
                login_path: /espace/etudiant/login
                check_path: /espace/etudiant/login_check
                default_target_path: /espace/etudiant/
            provider: app_student_provider
            logout:
                path: /espace/etudiant/logout
                target: /espace/etudiant/login

        parent_space:
            pattern: ^/espace/parent/
            anonymous: false
            form_login:
                login_path: /espace/parent/login
                check_path: /espace/parent/login_check
                default_target_path: /espace/parent/
            provider: app_parent_provider
            logout:
                path: /espace/parent/logout
                target: /espace/parent/login

        secure_area:
            pattern: ^/
            anonymous: false
            form_login: ~
            provider: our_db_provider
            logout:
                path: /logout
                target: /login
            switch_user: true

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~                

    role_hierarchy:
        ROLE_PARENT:                ROLE_USER
        ROLE_ETUDIANT:              ROLE_USER
        ROLE_SAISIE:                ROLE_USER
        ROLE_COMMUNICATION:         ROLE_USER
        ROLE_RESP_PEDAGOGIE:        ROLE_USER
        ROLE_RESPONSABLE:           ROLE_SAISIE
        ROLE_SAISIE_CARTE:          ROLE_SAISIE
        ROLE_RESP_SAISIE:           ROLE_SAISIE_CARTE
        ROLE_DIRECTEUR:             [ROLE_RESPONSABLE, ROLE_ADMIN, ROLE_RESP_SAISIE, ROLE_RESP_PEDAGOGIE]
        ROLE_SUP_DIRECTEUR:         ROLE_DIRECTEUR
        ROLE_ADMIN:                 ROLE_DIRECTEUR
        ROLE_SUPER_ADMIN:           [ROLE_SUP_DIRECTEUR, ROLE_RESP_SAISIE, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/espace/etudiant/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/espace/parent/login, roles: IS_AUTHENTICATED_ANONYMOUSLY ,requires_channel: http}
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY ,requires_channel: http}
        - { path: ^/utilisateur/changerMotPasse, roles: ROLE_USER, requires_channel: http }

        - { path: ^/groupes, roles: ROLE_SUPER_ADMIN, requires_channel: http }
        - { path: ^/utilisateur/supprimer, roles: ROLE_SUPER_ADMIN, requires_channel: http }

        - { path: ^/admin, roles: ROLE_SUPER_ADMIN , requires_channel: http}
        - { path: ^/utilisateur, roles: ROLE_SUP_DIRECTEUR, requires_channel: http }

        - { path: ^/etudiant/liste, roles: [ROLE_SAISIE, ROLE_COMMUNICATION] , requires_channel: http}
        - { path: ^/etudiant/ajouter, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/etudiant/fiche, roles: [ROLE_SAISIE, ROLE_COMMUNICATION] , requires_channel: http}
        - { path: ^/etudiant/rechercher, roles: [ROLE_SAISIE, ROLE_COMMUNICATION], requires_channel: http }
        - { path: ^/etudiant/classe/ajouter, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/etudiant/paiement/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/etudiant/paiement/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/etudiant/paiement, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/paiement/ajouter, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/autre-paiement/ajouter, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/cours/ajouter, roles: ROLE_SAISIE, requires_channel: http }

        - { path: ^/etudiant/modifier, roles: [ROLE_DIRECTEUR, ROLE_RESP_SAISIE] , requires_channel: http}
        - { path: ^/etudiant/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http}
        - { path: ^/etudiant/classe/modifier, roles: [ROLE_DIRECTEUR, ROLE_RESP_SAISIE], requires_channel: http }
        - { path: ^/etudiant/classe/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/dossier/supprimer, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/dossier/, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/banque/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/classe/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/classe/supprimer, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/matiere/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/anneeScolaire/modifier, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/anneeScolaire/supprimer, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/cycle/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/filiere/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/suivi/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/suivi/supprimer, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/professeur/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/professeur/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/profMatiere/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/cours/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/cours/supprimer, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/paiement/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/paiement/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/autre-paiement/modifier, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/autre-paiement/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }
        - { path: ^/depense/modifier, roles: ROLE_DIRECTEUR , requires_channel: http}
        - { path: ^/depense/supprimer, roles: ROLE_DIRECTEUR, requires_channel: http }

        - { path: ^/banque, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/classe/, roles: [ROLE_RESPONSABLE, ROLE_RESP_PEDAGOGIE], requires_channel: http}
        - { path: ^/matiere, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/classeMatiere/modifier, roles: ROLE_RESPONSABLE, requires_channel: http}
        - { path: ^/classeMatiere/supprimer, roles: ROLE_RESPONSABLE, requires_channel: http}
        - { path: ^/classeMatiere, roles: [ROLE_RESPONSABLE, ROLE_RESP_PEDAGOGIE], requires_channel: http}
        - { path: ^/anneeScolaire, roles: ROLE_RESPONSABLE , requires_channel: http}
        - { path: ^/cycle, roles: ROLE_RESPONSABLE , requires_channel: http}
        - { path: ^/filiere, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/etudiant, roles: [ROLE_RESPONSABLE, ROLE_RESP_SAISIE], requires_channel: http}
        - { path: ^/paiement, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/autre-paiement, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/depense, roles: ROLE_RESPONSABLE }
        - { path: ^/professeur, roles: [ROLE_RESPONSABLE, ROLE_SAISIE], requires_channel: http }
        - { path: ^/profMatiere, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/cours, roles: [ROLE_RESPONSABLE, ROLE_SAISIE] , requires_channel: http}
        - { path: ^/suivi, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/etats, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/etat/liste_etudiants_par_classe$, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/etat/liste_paiements_entre_deux_dates$, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/etat/liste_etudiants_par_classe_et_seuil, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/etat/liste_etudiants_par_classe_password, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/etat/paiement, roles: ROLE_SAISIE , requires_channel: http}
        - { path: ^/etat/autrepaiement, roles: ROLE_SAISIE, requires_channel: http }
        - { path: ^/etat, roles: ROLE_RESPONSABLE , requires_channel: http}
        - { path: ^/parent, roles: [ROLE_SAISIE, ROLE_COMMUNICATION], requires_channel: http }
        - { path: ^/bulletin, roles: [ROLE_RESPONSABLE, ROLE_PARENT], requires_channel: http }
        - { path: ^/autredocument, roles: ROLE_RESPONSABLE, requires_channel: http }
        - { path: ^/lecon/edit, roles: ROLE_RESPONSABLE, requires_channel: http}
        - { path: ^/lecon/delete, roles: ROLE_RESPONSABLE, requires_channel: http}
        - { path: ^/lecon, roles: [ROLE_RESPONSABLE, ROLE_RESP_PEDAGOGIE], requires_channel: http }
        - { path: ^/, roles: ROLE_USER , requires_channel: http}
